language: python

before_install:
 - pip install --upgrade pip setuptools
 - pip install planemo

script:
 - planemo lint ${TRAVIS_BUILD_DIR}/tools/msp2db
 - planemo test  --conda_ensure_channels computational-metabolomics,tomnl,iuc,bioconda,conda-forge,defaults --galaxy_python_version 3.8 
 
