{% set name = "msp2db" %}
{% set version = "0.0.14" %}


package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/computational-metabolomics/msp2db

build:
  number: 0
  noarch: python
  entry_points:
    - msp2db = msp2db.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pubchempy
    - six

test:
  imports:
    - msp2db
    - tests
  commands:
    - msp2db --help

about:
  home: https://github.com/computational-metabolomics/msp2db
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: LICENSE
  summary: Python package to create an SQLite database from a collection of MSP mass spectromertry spectra files. Currently works with MSP files formated as MassBank records or as MoNA records. The resulting SQLite database can be used for spectral matching with msPurity Bioconductor R package, 

extra:
  recipe-maintainers:
    - RJMW
    - tomnl
